# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 05:58
from __future__ import unicode_literals

import autoslug.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, verbose_name='UUID')),
                ('client_id', models.CharField(editable=False, max_length=30, null=True)),
                ('name', models.CharField(max_length=96, verbose_name="Client's Name")),
                ('phone', models.CharField(max_length=16, verbose_name='Phone No')),
                ('phone_relative', models.CharField(max_length=16, verbose_name="Relative's Phone No")),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('randomised', models.BooleanField(default=False)),
                ('random_selection', models.BooleanField(default=False, verbose_name='Random Selection')),
                ('called', models.BooleanField(default=False, verbose_name='Contacted?')),
                ('available', models.BooleanField(default=False, verbose_name='Available?')),
                ('came_day7', models.BooleanField(default=False, verbose_name='Came to clinic at 7th day after delivery?')),
                ('came_day14', models.BooleanField(default=False, verbose_name='Came to clinic at 14th day after delivery?')),
                ('came_day28', models.BooleanField(default=False, verbose_name='Came to clinic at 28th day after delivery?')),
            ],
        ),
        migrations.CreateModel(
            name='FormConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Form Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('double_verification', models.BooleanField(default=False, verbose_name='Double Verification?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('client_id', models.CharField(editable=False, max_length=30, null=True, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.FormConfig')),
            ],
        ),
    ]
