# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledclients',
            name='came_day14',
        ),
        migrations.AddField(
            model_name='enrolledclients',
            name='called_on_missed_visit2',
            field=models.BooleanField(default=False, verbose_name='Called on missed visit 2?'),
        ),
        migrations.AddField(
            model_name='enrolledclients',
            name='vailable_on_missed_visit2',
            field=models.BooleanField(default=False, verbose_name='Available on missed visit 2 call?'),
        ),
    ]
