# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20161219_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledclients',
            old_name='vailable_on_missed_visit2',
            new_name='available_on_missed_visit2',
        ),
    ]
