# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_formdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='interview_date',
            field=models.DateTimeField(null=True, verbose_name='Interview Date'),
        ),
    ]
